- name: update cache #apt update
  apt:
    update_cache: yes

- name: install nginx #apt-install nginx
  apt:
    name: nginx

- name: copy contents from website to /var/www/html
  copy:
    src: files/website/
    dest: /var/www/html/
    directory_mode:
  tags:
    - dircontent