- name: update cache #apt update
  apt:
    update_cache: yes

- name: install nginx #apt-install nginx
  apt:
    name: nginx

- name: create directory
  file: 
    path: /website
    state: directory

- name: copy website folder
  copy:
    src: "{{ item }}" 
    dest: /var/www/html
  with_fileglob:
    - "files/html/*"
